/**
 * Real club line-ups (current era), keyed by the club code used in clubs.ts.
 * GK first, UPPERCASE ASCII for the in-game font (the radio Title-cases them).
 * Used by clubs.ts to give club matches real player names, like the national
 * and DEFI squads.
 */
export const CLUB_SQUADS: Record<string, string[]> = {
  // Ligue 1
  PSG: ["DONNARUMMA", "HAKIMI", "MARQUINHOS", "PACHO", "N.MENDES", "VITINHA", "J.NEVES", "F.RUIZ", "DEMBELE", "KVARATSKHELIA", "BARCOLA"],
  OM: ["RULLI", "MURILLO", "BALERDI", "KONDOGBIA", "MERLIN", "HOJBJERG", "RABIOT", "GREENWOOD", "HARIT", "L.HENRIQUE", "GOUIRI"],
  OL: ["PERRI", "MAITLAND", "NIAKHATE", "TAGLIAFICO", "ABNER", "TOLISSO", "MATIC", "CHERKI", "M.FOFANA", "MIKAUTADZE", "LACAZETTE"],
  ASM: ["KOHN", "VANDERSON", "SALISU", "KEHRER", "C.HENRIQUE", "ZAKARIA", "T.CAMARA", "MINAMINO", "AKLIOUCHE", "BEN.SEGHIR", "EMBOLO"],
  LOSC: ["CHEVALIER", "MEUNIER", "DIAKITE", "ALEXSANDRO", "GUDMUNDSSON", "A.ANDRE", "BENTALEB", "CABELLA", "HARALDSSON", "J.DAVID", "ZHEGROVA"],
  OGCN: ["BULKA", "CLAUSS", "DANTE", "BARD", "A.MENDY", "SANSON", "BOUANANI", "DIOP", "GUESSAND", "MOFFI", "LABORDE"],
  RCL: ["LECA", "GRADIT", "MEDINA", "DANSO", "FRANKOWSKI", "N.MENDY", "A.DIOUF", "THOMASSON", "SOTOCA", "M.SAID", "WAHI"],
  SRFC: ["MANDANDA", "ASSIGNON", "THEATE", "BROWN", "TRUFFERT", "SANTAMARIA", "MATUSIWA", "BLAS", "GRONBAEK", "KALIMUENDO", "BOURIGEAUD"],
  RCSA: ["PENDERS", "NANASI", "SYLLA", "DOUKOURE", "DELAINE", "SANTOS", "A.SANTOS", "DIONG", "EMEGHA", "BAKWA", "LEMARECHAL"],
  TFC: ["RESTES", "KAMANZI", "NICOLAISEN", "McKENZIE", "SIDIBE", "CASSERES", "SPIERINGS", "GBOHO", "MAGRI", "DONNUM", "VOSSAH"],
  FCN: ["LAFONT", "COCO", "ZEZE", "CASTELLETTO", "PALLOIS", "CHIRIVELLA", "M.SISSOKO", "D.AUGUSTO", "SIMON", "M.MOHAMED", "ABLINE"],
  SB29: ["BIZOT", "LALA", "CHARDONNET", "LE.CARDINAL", "LOCKO", "MAGNETTI", "LEES.MELOU", "DEL.CASTILLO", "DOUMBIA", "AJORQUE", "SIMA"],
  // Premier League
  ARS: ["RAYA", "WHITE", "SALIBA", "GABRIEL", "CALAFIORI", "RICE", "PARTEY", "ODEGAARD", "SAKA", "HAVERTZ", "MARTINELLI"],
  LIV: ["ALISSON", "ALEXANDER.ARNOLD", "KONATE", "VAN.DIJK", "ROBERTSON", "GRAVENBERCH", "MAC.ALLISTER", "SZOBOSZLAI", "SALAH", "L.DIAZ", "NUNEZ"],
  MCI: ["EDERSON", "WALKER", "R.DIAS", "GVARDIOL", "STONES", "RODRI", "DE.BRUYNE", "B.SILVA", "FODEN", "HAALAND", "DOKU"],
  MUN: ["ONANA", "MAZRAOUI", "DE.LIGT", "L.MARTINEZ", "DALOT", "MAINOO", "B.FERNANDES", "UGARTE", "GARNACHO", "HOJLUND", "RASHFORD"],
  CHE: ["SANCHEZ", "GUSTO", "FOFANA", "COLWILL", "CUCURELLA", "CAICEDO", "E.FERNANDEZ", "PALMER", "MADUEKE", "N.JACKSON", "NETO"],
  TOT: ["VICARIO", "PORRO", "ROMERO", "VAN.DE.VEN", "UDOGIE", "BENTANCUR", "BISSOUMA", "MADDISON", "KULUSEVSKI", "SON", "SOLANKE"],
  // La Liga
  RMA: ["COURTOIS", "CARVAJAL", "MILITAO", "RUDIGER", "F.MENDY", "TCHOUAMENI", "VALVERDE", "BELLINGHAM", "VINICIUS", "MBAPPE", "RODRYGO"],
  BAR: ["SZCZESNY", "KOUNDE", "CUBARSI", "I.MARTINEZ", "BALDE", "DE.JONG", "PEDRI", "F.LOPEZ", "YAMAL", "LEWANDOWSKI", "RAPHINHA"],
  ATM: ["OBLAK", "MOLINA", "J.GIMENEZ", "LENGLET", "GALAN", "KOKE", "DE.PAUL", "BARRIOS", "GRIEZMANN", "J.ALVAREZ", "SORLOTH"],
  // Serie A
  INT: ["SOMMER", "PAVARD", "ACERBI", "BASTONI", "DUMFRIES", "BARELLA", "CALHANOGLU", "MKHITARYAN", "DIMARCO", "THURAM", "L.MARTINEZ"],
  MIL: ["MAIGNAN", "E.ROYAL", "TOMORI", "GABBIA", "T.HERNANDEZ", "FOFANA", "REIJNDERS", "PULISIC", "LOFTUS.CHEEK", "LEAO", "MORATA"],
  JUV: ["DI.GREGORIO", "SAVONA", "GATTI", "KALULU", "CAMBIASO", "LOCATELLI", "K.THURAM", "KOOPMEINERS", "YILDIZ", "VLAHOVIC", "CONCEICAO"],
  NAP: ["MERET", "DI.LORENZO", "RRAHMANI", "BUONGIORNO", "OLIVERA", "ANGUISSA", "LOBOTKA", "McTOMINAY", "POLITANO", "LUKAKU", "NERES"],
  // Bundesliga
  FCB: ["NEUER", "KIMMICH", "UPAMECANO", "DIER", "DAVIES", "PALHINHA", "GORETZKA", "MUSIALA", "OLISE", "KANE", "SANE"],
  BVB: ["KOBEL", "RYERSON", "SCHLOTTERBECK", "ANTON", "BENSEBAINI", "GROSS", "SABITZER", "BRANDT", "GITTENS", "GUIRASSY", "ADEYEMI"],
  B04: ["HRADECKY", "TAPSOBA", "TAH", "HINCAPIE", "FRIMPONG", "GRIMALDO", "XHAKA", "ANDRICH", "WIRTZ", "SCHICK", "BONIFACE"],
  // Autres
  GAL: ["MUSLERA", "SALLAI", "D.SANCHEZ", "BARDAKCI", "JELERT", "TORREIRA", "DEMIRBAY", "B.YILMAZ", "OSIMHEN", "ICARDI", "SANE"],
  NAS: ["BENTO", "AL.GHANNAM", "LAPORTE", "SIMAKAN", "TELLES", "BROZOVIC", "OTAVIO", "AL.KHAIBARI", "MANE", "RONALDO", "ANGELO"],
  MIA: ["USTARI", "WEIGANDT", "AVILES", "FALCON", "JORDI.ALBA", "BUSQUETS", "REDONDO", "CREMASCHI", "MESSI", "L.SUAREZ", "SEGOVIA"],
};
