/**
 * Real club line-ups (current era), keyed by the club code used in clubs.ts.
 * GK first; the first 11 are the XI, the rest are the bench. UPPERCASE ASCII for
 * the in-game font (the radio Title-cases them). Used by clubs.ts.
 */
export const CLUB_SQUADS: Record<string, string[]> = {
  // Ligue 1
  PSG: ["DONNARUMMA", "HAKIMI", "MARQUINHOS", "PACHO", "N.MENDES", "VITINHA", "J.NEVES", "F.RUIZ", "DEMBELE", "KVARATSKHELIA", "BARCOLA", "SAFONOV", "BERALDO", "MAYULU", "LEE", "ZAIRE.EMERY", "G.RAMOS"],
  OM: ["RULLI", "MURILLO", "BALERDI", "KONDOGBIA", "MERLIN", "HOJBJERG", "RABIOT", "GREENWOOD", "HARIT", "L.HENRIQUE", "GOUIRI", "DE.LANGE", "LODI", "CORNELIUS", "RONGIER", "MAUPAY", "WAHI"],
  OL: ["PERRI", "MAITLAND", "NIAKHATE", "TAGLIAFICO", "ABNER", "TOLISSO", "MATIC", "CHERKI", "M.FOFANA", "MIKAUTADZE", "LACAZETTE", "DESCAMPS", "MATA", "CAQUERET", "VERETOUT", "NUAMAH", "ORBAN"],
  ASM: ["KOHN", "VANDERSON", "SALISU", "KEHRER", "C.HENRIQUE", "ZAKARIA", "T.CAMARA", "MINAMINO", "AKLIOUCHE", "BEN.SEGHIR", "EMBOLO", "MAJECKI", "MAWISSA", "MATAZO", "GOLOVIN", "DIATTA", "BALOGUN"],
  LOSC: ["CHEVALIER", "MEUNIER", "DIAKITE", "ALEXSANDRO", "GUDMUNDSSON", "A.ANDRE", "BENTALEB", "CABELLA", "HARALDSSON", "J.DAVID", "ZHEGROVA", "OZER", "MANDI", "T.SANTOS", "BODART", "MUKAU", "FDEZ.PARDO"],
  OGCN: ["BULKA", "CLAUSS", "DANTE", "BARD", "A.MENDY", "SANSON", "BOUANANI", "DIOP", "GUESSAND", "MOFFI", "LABORDE", "DIOUF", "ABDI", "LOTOMBA", "BONARD", "JANSSON", "CHO"],
  RCL: ["LECA", "GRADIT", "MEDINA", "DANSO", "FRANKOWSKI", "N.MENDY", "A.DIOUF", "THOMASSON", "SOTOCA", "M.SAID", "WAHI", "KOFFI", "KHUSANOV", "ABDUL.SAMED", "FULGINI", "LABEAU", "EDOUARD"],
  SRFC: ["MANDANDA", "ASSIGNON", "THEATE", "BROWN", "TRUFFERT", "SANTAMARIA", "MATUSIWA", "BLAS", "GRONBAEK", "KALIMUENDO", "BOURIGEAUD", "SAMBA", "WOOH", "SEIDU", "R.JAMES", "LEPAUL", "MEITE"],
  RCSA: ["PENDERS", "NANASI", "SYLLA", "DOUKOURE", "DELAINE", "SANTOS", "A.SANTOS", "DIONG", "EMEGHA", "BAKWA", "LEMARECHAL", "SIVERT", "HOGSBERG", "LUIS", "SEBAS", "EL.MOURABET", "PAGE"],
  TFC: ["RESTES", "KAMANZI", "NICOLAISEN", "McKENZIE", "SIDIBE", "CASSERES", "SPIERINGS", "GBOHO", "MAGRI", "DONNUM", "VOSSAH", "HAUG", "COSTA", "SIERRO", "EDJOUMA", "SUAZO", "EMERSIN"],
  FCN: ["LAFONT", "COCO", "ZEZE", "CASTELLETTO", "PALLOIS", "CHIRIVELLA", "M.SISSOKO", "D.AUGUSTO", "SIMON", "M.MOHAMED", "ABLINE", "LOPES", "TATI", "LEROUX", "BENHATTAB", "EL.ARABI", "GUIRASSY"],
  SB29: ["BIZOT", "LALA", "CHARDONNET", "LE.CARDINAL", "LOCKO", "MAGNETTI", "LEES.MELOU", "DEL.CASTILLO", "DOUMBIA", "AJORQUE", "SIMA", "COUDERT", "HAIDARA", "FERNANDES", "C.MARTIN", "P.LAGE", "SATRIANO"],
  // Premier League
  ARS: ["RAYA", "WHITE", "SALIBA", "GABRIEL", "CALAFIORI", "RICE", "PARTEY", "ODEGAARD", "SAKA", "HAVERTZ", "MARTINELLI", "NETO", "TIMBER", "KIWIOR", "ZINCHENKO", "MERINO", "TROSSARD"],
  LIV: ["ALISSON", "ALEXANDER.ARNOLD", "KONATE", "VAN.DIJK", "ROBERTSON", "GRAVENBERCH", "MAC.ALLISTER", "SZOBOSZLAI", "SALAH", "L.DIAZ", "NUNEZ", "KELLEHER", "BRADLEY", "QUANSAH", "ENDO", "JONES", "CHIESA"],
  MCI: ["EDERSON", "WALKER", "R.DIAS", "GVARDIOL", "STONES", "RODRI", "DE.BRUYNE", "B.SILVA", "FODEN", "HAALAND", "DOKU", "ORTEGA", "AKE", "LEWIS", "KOVACIC", "SAVINHO", "GREALISH"],
  MUN: ["ONANA", "MAZRAOUI", "DE.LIGT", "L.MARTINEZ", "DALOT", "MAINOO", "B.FERNANDES", "UGARTE", "GARNACHO", "HOJLUND", "RASHFORD", "BAYINDIR", "YORO", "SHAW", "CASEMIRO", "ERIKSEN", "ZIRKZEE"],
  CHE: ["SANCHEZ", "GUSTO", "FOFANA", "COLWILL", "CUCURELLA", "CAICEDO", "E.FERNANDEZ", "PALMER", "MADUEKE", "N.JACKSON", "NETO", "JORGENSEN", "BADIASHILE", "ACHEAMPONG", "DEWSBURY.HALL", "NKUNKU", "F.JIMENEZ"],
  TOT: ["VICARIO", "PORRO", "ROMERO", "VAN.DE.VEN", "UDOGIE", "BENTANCUR", "BISSOUMA", "MADDISON", "KULUSEVSKI", "SON", "SOLANKE", "FORSTER", "DRAGUSIN", "SPENCE", "BERGVALL", "JOHNSON", "RICHARLISON"],
  // La Liga
  RMA: ["COURTOIS", "CARVAJAL", "MILITAO", "RUDIGER", "F.MENDY", "TCHOUAMENI", "VALVERDE", "BELLINGHAM", "VINICIUS", "MBAPPE", "RODRYGO", "LUNIN", "L.VAZQUEZ", "ASENCIO", "CEBALLOS", "MODRIC", "ENDRICK"],
  BAR: ["SZCZESNY", "KOUNDE", "CUBARSI", "I.MARTINEZ", "BALDE", "DE.JONG", "PEDRI", "F.LOPEZ", "YAMAL", "LEWANDOWSKI", "RAPHINHA", "TER.STEGEN", "E.GARCIA", "ARAUJO", "CASADO", "D.OLMO", "F.TORRES"],
  ATM: ["OBLAK", "MOLINA", "J.GIMENEZ", "LENGLET", "GALAN", "KOKE", "DE.PAUL", "BARRIOS", "GRIEZMANN", "J.ALVAREZ", "SORLOTH", "MUSSO", "LLORENTE", "REINILDO", "GALLAGHER", "RIQUELME", "CORREA"],
  // Serie A
  INT: ["SOMMER", "PAVARD", "ACERBI", "BASTONI", "DUMFRIES", "BARELLA", "CALHANOGLU", "MKHITARYAN", "DIMARCO", "THURAM", "L.MARTINEZ", "J.MARTINEZ", "DE.VRIJ", "DARMIAN", "ZIELINSKI", "FRATTESI", "TAREMI"],
  MIL: ["MAIGNAN", "E.ROYAL", "TOMORI", "GABBIA", "T.HERNANDEZ", "FOFANA", "REIJNDERS", "PULISIC", "LOFTUS.CHEEK", "LEAO", "MORATA", "TORRIANI", "THIAW", "TERRACCIANO", "MUSAH", "CHUKWUEZE", "ABRAHAM"],
  JUV: ["DI.GREGORIO", "SAVONA", "GATTI", "KALULU", "CAMBIASO", "LOCATELLI", "K.THURAM", "KOOPMEINERS", "YILDIZ", "VLAHOVIC", "CONCEICAO", "PERIN", "KELLY", "R.VEIGA", "DOUGLAS.LUIZ", "WEAH", "KOLO.MUANI"],
  NAP: ["MERET", "DI.LORENZO", "RRAHMANI", "BUONGIORNO", "OLIVERA", "ANGUISSA", "LOBOTKA", "McTOMINAY", "POLITANO", "LUKAKU", "NERES", "CAPRILE", "JUAN.JESUS", "MARIN", "GILMOUR", "RASPADORI", "SIMEONE"],
  // Bundesliga
  FCB: ["NEUER", "KIMMICH", "UPAMECANO", "DIER", "DAVIES", "PALHINHA", "GORETZKA", "MUSIALA", "OLISE", "KANE", "SANE", "ULREICH", "ITO", "KIM", "LAIMER", "GNABRY", "COMAN"],
  BVB: ["KOBEL", "RYERSON", "SCHLOTTERBECK", "ANTON", "BENSEBAINI", "GROSS", "SABITZER", "BRANDT", "GITTENS", "GUIRASSY", "ADEYEMI", "MEYER", "SULE", "EMRE.CAN", "NMECHA", "BEIER", "DURANVILLE"],
  B04: ["HRADECKY", "TAPSOBA", "TAH", "HINCAPIE", "FRIMPONG", "GRIMALDO", "XHAKA", "ANDRICH", "WIRTZ", "SCHICK", "BONIFACE", "KOVAR", "BADE", "KOSSOUNOU", "PALACIOS", "T.GARCIA", "HLOZEK"],
  // Autres
  GAL: ["MUSLERA", "SALLAI", "D.SANCHEZ", "BARDAKCI", "JELERT", "TORREIRA", "DEMIRBAY", "B.YILMAZ", "OSIMHEN", "ICARDI", "SANE", "GUNAY", "NELSSON", "KAAN", "G.SARA", "MERTENS", "AKGUN"],
  NAS: ["BENTO", "AL.GHANNAM", "LAPORTE", "SIMAKAN", "TELLES", "BROZOVIC", "OTAVIO", "AL.KHAIBARI", "MANE", "RONALDO", "ANGELO", "AL.AQIDI", "LAJAMI", "AL.AMRI", "AL.NAJEI", "WESLEY", "GHISLAIN"],
  MIA: ["USTARI", "WEIGANDT", "AVILES", "FALCON", "JORDI.ALBA", "BUSQUETS", "REDONDO", "CREMASCHI", "MESSI", "L.SUAREZ", "SEGOVIA", "CALLENDER", "KRYVTSOV", "GOMEZ", "ALLEN", "B.RODRIGUEZ", "R.PIZARRO"],
};
