/**
 * Curated real-player club squads (first 11 = starting XI in the
 * GB,DD,DC,DC,DG,MDC,MC,MOC,AG,BU,AD template order, then the bench).
 */

export interface RealPlayer {
  name: string;
  pos: string;
  rating: number;
}

export const REAL_CLUB_SQUADS: Record<string, RealPlayer[]> = {
  "Paris Saint-Germain": [
    { name: "Lucas Chevalier", pos: "GB", rating: 85 },
    { name: "Achraf Hakimi", pos: "DD", rating: 89 },
    { name: "Marquinhos", pos: "DC", rating: 87 },
    { name: "Willian Pacho", pos: "DC", rating: 86 },
    { name: "Nuno Mendes", pos: "DG", rating: 87 },
    { name: "Vitinha", pos: "MDC", rating: 89 },
    { name: "Joao Neves", pos: "MC", rating: 87 },
    { name: "Warren Zaire-Emery", pos: "MOC", rating: 84 },
    { name: "Khvicha Kvaratskhelia", pos: "AG", rating: 89 },
    { name: "Ousmane Dembele", pos: "BU", rating: 91 },
    { name: "Desire Doue", pos: "AD", rating: 87 },
    { name: "Matvey Safonov", pos: "GB", rating: 80 },
    { name: "Illia Zabarnyi", pos: "DC", rating: 84 },
    { name: "Lucas Beraldo", pos: "DC", rating: 79 },
    { name: "Fabian Ruiz", pos: "MC", rating: 85 },
    { name: "Kang-in Lee", pos: "MOC", rating: 83 },
    { name: "Bradley Barcola", pos: "AG", rating: 86 },
    { name: "Goncalo Ramos", pos: "BU", rating: 84 },
  ],
  "Olympique de Marseille": [
    { name: "Geronimo Rulli", pos: "GB", rating: 84 },
    { name: "Timothy Weah", pos: "DD", rating: 81 },
    { name: "Leonardo Balerdi", pos: "DC", rating: 83 },
    { name: "Nayef Aguerd", pos: "DC", rating: 82 },
    { name: "Ulisses Garcia", pos: "DG", rating: 78 },
    { name: "Pierre-Emile Hojbjerg", pos: "MDC", rating: 83 },
    { name: "Geoffrey Kondogbia", pos: "MC", rating: 79 },
    { name: "Matt O'Riley", pos: "MOC", rating: 80 },
    { name: "Igor Paixao", pos: "AG", rating: 81 },
    { name: "Pierre-Emerick Aubameyang", pos: "BU", rating: 83 },
    { name: "Mason Greenwood", pos: "AD", rating: 86 },
    { name: "Jeffrey de Lange", pos: "GB", rating: 76 },
    { name: "Amir Murillo", pos: "DD", rating: 79 },
    { name: "Derek Cornelius", pos: "DC", rating: 78 },
    { name: "Angel Gomes", pos: "MC", rating: 80 },
    { name: "Bilal Nadir", pos: "MOC", rating: 77 },
    { name: "Amine Gouiri", pos: "BU", rating: 82 },
    { name: "Neal Maupay", pos: "BU", rating: 77 },
  ],
  "Olympique Lyonnais": [
    { name: "Lucas Perri", pos: "GB", rating: 81 },
    { name: "Ainsley Maitland-Niles", pos: "DD", rating: 79 },
    { name: "Clinton Mata", pos: "DC", rating: 79 },
    { name: "Moussa Niakhate", pos: "DC", rating: 80 },
    { name: "Nicolas Tagliafico", pos: "DG", rating: 81 },
    { name: "Tanner Tessmann", pos: "MDC", rating: 78 },
    { name: "Corentin Tolisso", pos: "MC", rating: 81 },
    { name: "Pavel Sulc", pos: "MOC", rating: 79 },
    { name: "Malick Fofana", pos: "AG", rating: 83 },
    { name: "Martin Satriano", pos: "BU", rating: 76 },
    { name: "Afonso Moreira", pos: "AD", rating: 76 },
    { name: "Dominik Greif", pos: "GB", rating: 77 },
    { name: "Kluivert Abner", pos: "DG", rating: 76 },
    { name: "Ruben Kluivert", pos: "DC", rating: 76 },
    { name: "Tyler Morton", pos: "MC", rating: 78 },
    { name: "Rachid Ghezzal", pos: "AD", rating: 74 },
    { name: "Georges Mikautadze", pos: "BU", rating: 82 },
    { name: "Enzo Molebe", pos: "BU", rating: 73 },
  ],
  "AS Monaco": [
    { name: "Lukas Hradecky", pos: "GB", rating: 80 },
    { name: "Vanderson", pos: "DD", rating: 82 },
    { name: "Thilo Kehrer", pos: "DC", rating: 79 },
    { name: "Mohammed Salisu", pos: "DC", rating: 79 },
    { name: "Caio Henrique", pos: "DG", rating: 82 },
    { name: "Denis Zakaria", pos: "MDC", rating: 84 },
    { name: "Lamine Camara", pos: "MC", rating: 81 },
    { name: "Aleksandr Golovin", pos: "MOC", rating: 83 },
    { name: "Ansu Fati", pos: "AG", rating: 79 },
    { name: "Folarin Balogun", pos: "BU", rating: 81 },
    { name: "Maghnes Akliouche", pos: "AD", rating: 84 },
    { name: "Philipp Kohn", pos: "GB", rating: 78 },
    { name: "Christian Mawissa", pos: "DC", rating: 78 },
    { name: "Jordan Teze", pos: "DD", rating: 78 },
    { name: "Paul Pogba", pos: "MC", rating: 79 },
    { name: "Takumi Minamino", pos: "MOC", rating: 80 },
    { name: "Mika Biereth", pos: "BU", rating: 80 },
    { name: "Krepin Diatta", pos: "AD", rating: 78 },
  ],
  Arsenal: [
    { name: "David Raya", pos: "GB", rating: 87 },
    { name: "Jurrien Timber", pos: "DD", rating: 84 },
    { name: "William Saliba", pos: "DC", rating: 89 },
    { name: "Gabriel Magalhaes", pos: "DC", rating: 87 },
    { name: "Riccardo Calafiori", pos: "DG", rating: 82 },
    { name: "Martin Zubimendi", pos: "MDC", rating: 86 },
    { name: "Declan Rice", pos: "MC", rating: 88 },
    { name: "Martin Odegaard", pos: "MOC", rating: 88 },
    { name: "Gabriel Martinelli", pos: "AG", rating: 84 },
    { name: "Viktor Gyokeres", pos: "BU", rating: 87 },
    { name: "Bukayo Saka", pos: "AD", rating: 89 },
    { name: "Kepa Arrizabalaga", pos: "GB", rating: 79 },
    { name: "Ben White", pos: "DD", rating: 83 },
    { name: "Jakub Kiwior", pos: "DC", rating: 80 },
    { name: "Mikel Merino", pos: "MC", rating: 83 },
    { name: "Ethan Nwaneri", pos: "MOC", rating: 81 },
    { name: "Leandro Trossard", pos: "AG", rating: 83 },
    { name: "Noni Madueke", pos: "AD", rating: 82 },
  ],
  Liverpool: [
    { name: "Alisson Becker", pos: "GB", rating: 88 },
    { name: "Jeremie Frimpong", pos: "DD", rating: 84 },
    { name: "Virgil van Dijk", pos: "DC", rating: 89 },
    { name: "Ibrahima Konate", pos: "DC", rating: 86 },
    { name: "Milos Kerkez", pos: "DG", rating: 84 },
    { name: "Ryan Gravenberch", pos: "MDC", rating: 86 },
    { name: "Alexis Mac Allister", pos: "MC", rating: 87 },
    { name: "Florian Wirtz", pos: "MOC", rating: 90 },
    { name: "Cody Gakpo", pos: "AG", rating: 84 },
    { name: "Alexander Isak", pos: "BU", rating: 88 },
    { name: "Mohamed Salah", pos: "AD", rating: 90 },
    { name: "Giorgi Mamardashvili", pos: "GB", rating: 82 },
    { name: "Conor Bradley", pos: "DD", rating: 81 },
    { name: "Joe Gomez", pos: "DC", rating: 80 },
    { name: "Curtis Jones", pos: "MC", rating: 81 },
    { name: "Dominik Szoboszlai", pos: "MOC", rating: 85 },
    { name: "Hugo Ekitike", pos: "BU", rating: 83 },
    { name: "Federico Chiesa", pos: "AD", rating: 79 },
  ],
  "Manchester City": [
    { name: "Gianluigi Donnarumma", pos: "GB", rating: 89 },
    { name: "Matheus Nunes", pos: "DD", rating: 80 },
    { name: "Ruben Dias", pos: "DC", rating: 87 },
    { name: "Josko Gvardiol", pos: "DC", rating: 86 },
    { name: "Rayan Ait-Nouri", pos: "DG", rating: 83 },
    { name: "Rodri", pos: "MDC", rating: 90 },
    { name: "Bernardo Silva", pos: "MC", rating: 87 },
    { name: "Phil Foden", pos: "MOC", rating: 87 },
    { name: "Jeremy Doku", pos: "AG", rating: 85 },
    { name: "Erling Haaland", pos: "BU", rating: 92 },
    { name: "Savinho", pos: "AD", rating: 82 },
    { name: "James Trafford", pos: "GB", rating: 80 },
    { name: "John Stones", pos: "DC", rating: 85 },
    { name: "Nathan Ake", pos: "DC", rating: 82 },
    { name: "Tijjani Reijnders", pos: "MC", rating: 85 },
    { name: "Rayan Cherki", pos: "MOC", rating: 84 },
    { name: "Omar Marmoush", pos: "BU", rating: 84 },
    { name: "Nico Gonzalez", pos: "MC", rating: 82 },
  ],
  "Manchester United": [
    { name: "Senne Lammens", pos: "GB", rating: 79 },
    { name: "Diogo Dalot", pos: "DD", rating: 81 },
    { name: "Leny Yoro", pos: "DC", rating: 82 },
    { name: "Matthijs de Ligt", pos: "DC", rating: 83 },
    { name: "Patrick Dorgu", pos: "DG", rating: 79 },
    { name: "Casemiro", pos: "MDC", rating: 83 },
    { name: "Kobbie Mainoo", pos: "MC", rating: 82 },
    { name: "Bruno Fernandes", pos: "MOC", rating: 88 },
    { name: "Matheus Cunha", pos: "AG", rating: 85 },
    { name: "Benjamin Sesko", pos: "BU", rating: 84 },
    { name: "Bryan Mbeumo", pos: "AD", rating: 85 },
    { name: "Altay Bayindir", pos: "GB", rating: 78 },
    { name: "Noussair Mazraoui", pos: "DD", rating: 81 },
    { name: "Harry Maguire", pos: "DC", rating: 79 },
    { name: "Manuel Ugarte", pos: "MDC", rating: 81 },
    { name: "Mason Mount", pos: "MOC", rating: 78 },
    { name: "Amad Diallo", pos: "AD", rating: 83 },
    { name: "Joshua Zirkzee", pos: "BU", rating: 78 },
  ],
  Chelsea: [
    { name: "Robert Sanchez", pos: "GB", rating: 82 },
    { name: "Malo Gusto", pos: "DD", rating: 82 },
    { name: "Trevoh Chalobah", pos: "DC", rating: 81 },
    { name: "Levi Colwill", pos: "DC", rating: 82 },
    { name: "Marc Cucurella", pos: "DG", rating: 84 },
    { name: "Moises Caicedo", pos: "MDC", rating: 88 },
    { name: "Enzo Fernandez", pos: "MC", rating: 87 },
    { name: "Cole Palmer", pos: "MOC", rating: 90 },
    { name: "Alejandro Garnacho", pos: "AG", rating: 82 },
    { name: "Joao Pedro", pos: "BU", rating: 84 },
    { name: "Pedro Neto", pos: "AD", rating: 84 },
    { name: "Filip Jorgensen", pos: "GB", rating: 78 },
    { name: "Benoit Badiashile", pos: "DC", rating: 79 },
    { name: "Tosin Adarabioyo", pos: "DC", rating: 79 },
    { name: "Romeo Lavia", pos: "MC", rating: 80 },
    { name: "Estevao Willian", pos: "AD", rating: 84 },
    { name: "Jamie Gittens", pos: "AG", rating: 81 },
    { name: "Liam Delap", pos: "BU", rating: 80 },
  ],
  "Tottenham Hotspur": [
    { name: "Guglielmo Vicario", pos: "GB", rating: 84 },
    { name: "Pedro Porro", pos: "DD", rating: 84 },
    { name: "Cristian Romero", pos: "DC", rating: 87 },
    { name: "Micky van de Ven", pos: "DC", rating: 85 },
    { name: "Destiny Udogie", pos: "DG", rating: 82 },
    { name: "Joao Palhinha", pos: "MDC", rating: 84 },
    { name: "Rodrigo Bentancur", pos: "MC", rating: 82 },
    { name: "Xavi Simons", pos: "MOC", rating: 85 },
    { name: "Mohammed Kudus", pos: "AG", rating: 84 },
    { name: "Richarlison", pos: "BU", rating: 81 },
    { name: "Brennan Johnson", pos: "AD", rating: 83 },
    { name: "Antonin Kinsky", pos: "GB", rating: 78 },
    { name: "Kevin Danso", pos: "DC", rating: 80 },
    { name: "Djed Spence", pos: "DG", rating: 79 },
    { name: "Lucas Bergvall", pos: "MC", rating: 81 },
    { name: "Pape Matar Sarr", pos: "MC", rating: 81 },
    { name: "Wilson Odobert", pos: "AG", rating: 78 },
    { name: "Dominic Solanke", pos: "BU", rating: 82 },
  ],
  "Real Madrid": [
    { name: "Thibaut Courtois", pos: "GB", rating: 89 },
    { name: "Trent Alexander-Arnold", pos: "DD", rating: 87 },
    { name: "Eder Militao", pos: "DC", rating: 85 },
    { name: "Dean Huijsen", pos: "DC", rating: 85 },
    { name: "Alvaro Carreras", pos: "DG", rating: 83 },
    { name: "Aurelien Tchouameni", pos: "MDC", rating: 86 },
    { name: "Federico Valverde", pos: "MC", rating: 88 },
    { name: "Jude Bellingham", pos: "MOC", rating: 91 },
    { name: "Vinicius Junior", pos: "AG", rating: 90 },
    { name: "Kylian Mbappe", pos: "BU", rating: 92 },
    { name: "Rodrygo", pos: "AD", rating: 85 },
    { name: "Andriy Lunin", pos: "GB", rating: 82 },
    { name: "Dani Carvajal", pos: "DD", rating: 83 },
    { name: "Antonio Rudiger", pos: "DC", rating: 84 },
    { name: "Eduardo Camavinga", pos: "MC", rating: 84 },
    { name: "Arda Guler", pos: "MOC", rating: 84 },
    { name: "Franco Mastantuono", pos: "AD", rating: 82 },
    { name: "Endrick", pos: "BU", rating: 79 },
  ],
  "FC Barcelone": [
    { name: "Joan Garcia", pos: "GB", rating: 85 },
    { name: "Jules Kounde", pos: "DD", rating: 86 },
    { name: "Pau Cubarsi", pos: "DC", rating: 86 },
    { name: "Ronald Araujo", pos: "DC", rating: 84 },
    { name: "Alejandro Balde", pos: "DG", rating: 84 },
    { name: "Frenkie de Jong", pos: "MDC", rating: 85 },
    { name: "Pedri", pos: "MC", rating: 90 },
    { name: "Dani Olmo", pos: "MOC", rating: 85 },
    { name: "Raphinha", pos: "AG", rating: 89 },
    { name: "Robert Lewandowski", pos: "BU", rating: 88 },
    { name: "Lamine Yamal", pos: "AD", rating: 92 },
    { name: "Wojciech Szczesny", pos: "GB", rating: 82 },
    { name: "Eric Garcia", pos: "DC", rating: 80 },
    { name: "Andreas Christensen", pos: "DC", rating: 80 },
    { name: "Gavi", pos: "MC", rating: 83 },
    { name: "Fermin Lopez", pos: "MOC", rating: 82 },
    { name: "Marcus Rashford", pos: "AG", rating: 84 },
    { name: "Ferran Torres", pos: "BU", rating: 83 },
  ],
  "Atlético Madrid": [
    { name: "Jan Oblak", pos: "GB", rating: 87 },
    { name: "Marcos Llorente", pos: "DD", rating: 84 },
    { name: "Robin Le Normand", pos: "DC", rating: 83 },
    { name: "David Hancko", pos: "DC", rating: 82 },
    { name: "Matteo Ruggeri", pos: "DG", rating: 80 },
    { name: "Pablo Barrios", pos: "MDC", rating: 85 },
    { name: "Conor Gallagher", pos: "MC", rating: 82 },
    { name: "Alex Baena", pos: "MOC", rating: 85 },
    { name: "Nico Gonzalez", pos: "AG", rating: 82 },
    { name: "Julian Alvarez", pos: "BU", rating: 89 },
    { name: "Giuliano Simeone", pos: "AD", rating: 81 },
    { name: "Juan Musso", pos: "GB", rating: 78 },
    { name: "Jose Maria Gimenez", pos: "DC", rating: 82 },
    { name: "Javi Galan", pos: "DG", rating: 78 },
    { name: "Koke", pos: "MC", rating: 80 },
    { name: "Thiago Almada", pos: "MOC", rating: 82 },
    { name: "Antoine Griezmann", pos: "BU", rating: 85 },
    { name: "Alexander Sorloth", pos: "BU", rating: 83 },
  ],
  "Inter Milan": [
    { name: "Yann Sommer", pos: "GB", rating: 85 },
    { name: "Denzel Dumfries", pos: "DD", rating: 84 },
    { name: "Manuel Akanji", pos: "DC", rating: 84 },
    { name: "Alessandro Bastoni", pos: "DC", rating: 87 },
    { name: "Federico Dimarco", pos: "DG", rating: 85 },
    { name: "Hakan Calhanoglu", pos: "MDC", rating: 87 },
    { name: "Nicolo Barella", pos: "MC", rating: 88 },
    { name: "Henrikh Mkhitaryan", pos: "MOC", rating: 82 },
    { name: "Luis Henrique", pos: "AG", rating: 79 },
    { name: "Lautaro Martinez", pos: "BU", rating: 89 },
    { name: "Marcus Thuram", pos: "AD", rating: 87 },
    { name: "Josep Martinez", pos: "GB", rating: 80 },
    { name: "Stefan de Vrij", pos: "DC", rating: 82 },
    { name: "Carlos Augusto", pos: "DG", rating: 81 },
    { name: "Davide Frattesi", pos: "MC", rating: 82 },
    { name: "Petar Sucic", pos: "MC", rating: 80 },
    { name: "Ange-Yoan Bonny", pos: "BU", rating: 79 },
    { name: "Francesco Pio Esposito", pos: "BU", rating: 80 },
  ],
  "AC Milan": [
    { name: "Mike Maignan", pos: "GB", rating: 87 },
    { name: "Alexis Saelemaekers", pos: "DD", rating: 80 },
    { name: "Fikayo Tomori", pos: "DC", rating: 83 },
    { name: "Matteo Gabbia", pos: "DC", rating: 80 },
    { name: "Pervis Estupinan", pos: "DG", rating: 80 },
    { name: "Luka Modric", pos: "MDC", rating: 84 },
    { name: "Adrien Rabiot", pos: "MC", rating: 83 },
    { name: "Christopher Nkunku", pos: "MOC", rating: 83 },
    { name: "Rafael Leao", pos: "AG", rating: 87 },
    { name: "Santiago Gimenez", pos: "BU", rating: 81 },
    { name: "Christian Pulisic", pos: "AD", rating: 86 },
    { name: "Pietro Terracciano", pos: "GB", rating: 76 },
    { name: "Strahinja Pavlovic", pos: "DC", rating: 80 },
    { name: "Koni De Winter", pos: "DC", rating: 79 },
    { name: "Youssouf Fofana", pos: "MC", rating: 81 },
    { name: "Samuele Ricci", pos: "MC", rating: 80 },
    { name: "Ardon Jashari", pos: "MC", rating: 80 },
    { name: "Samuel Chukwueze", pos: "AD", rating: 79 },
  ],
  Juventus: [
    { name: "Michele Di Gregorio", pos: "GB", rating: 84 },
    { name: "Pierre Kalulu", pos: "DD", rating: 80 },
    { name: "Gleison Bremer", pos: "DC", rating: 86 },
    { name: "Federico Gatti", pos: "DC", rating: 81 },
    { name: "Andrea Cambiaso", pos: "DG", rating: 82 },
    { name: "Manuel Locatelli", pos: "MDC", rating: 83 },
    { name: "Khephren Thuram", pos: "MC", rating: 84 },
    { name: "Teun Koopmeiners", pos: "MOC", rating: 82 },
    { name: "Kenan Yildiz", pos: "AG", rating: 86 },
    { name: "Jonathan David", pos: "BU", rating: 84 },
    { name: "Francisco Conceicao", pos: "AD", rating: 82 },
    { name: "Mattia Perin", pos: "GB", rating: 79 },
    { name: "Daniele Rugani", pos: "DC", rating: 78 },
    { name: "Lloyd Kelly", pos: "DC", rating: 79 },
    { name: "Weston McKennie", pos: "MC", rating: 80 },
    { name: "Edon Zhegrova", pos: "AD", rating: 82 },
    { name: "Dusan Vlahovic", pos: "BU", rating: 84 },
    { name: "Lois Openda", pos: "BU", rating: 83 },
  ],
  Napoli: [
    { name: "Alex Meret", pos: "GB", rating: 83 },
    { name: "Giovanni Di Lorenzo", pos: "DD", rating: 84 },
    { name: "Amir Rrahmani", pos: "DC", rating: 83 },
    { name: "Alessandro Buongiorno", pos: "DC", rating: 84 },
    { name: "Mathias Olivera", pos: "DG", rating: 81 },
    { name: "Stanislav Lobotka", pos: "MDC", rating: 85 },
    { name: "Kevin De Bruyne", pos: "MC", rating: 87 },
    { name: "Scott McTominay", pos: "MOC", rating: 86 },
    { name: "David Neres", pos: "AG", rating: 82 },
    { name: "Rasmus Hojlund", pos: "BU", rating: 82 },
    { name: "Matteo Politano", pos: "AD", rating: 83 },
    { name: "Vanja Milinkovic-Savic", pos: "GB", rating: 82 },
    { name: "Sam Beukema", pos: "DC", rating: 82 },
    { name: "Leonardo Spinazzola", pos: "DG", rating: 79 },
    { name: "Andre-Frank Zambo Anguissa", pos: "MC", rating: 84 },
    { name: "Noa Lang", pos: "AG", rating: 81 },
    { name: "Lorenzo Lucca", pos: "BU", rating: 80 },
    { name: "Eljif Elmas", pos: "MOC", rating: 79 },
  ],
  "Bayern Munich": [
    { name: "Manuel Neuer", pos: "GB", rating: 85 },
    { name: "Konrad Laimer", pos: "DD", rating: 81 },
    { name: "Dayot Upamecano", pos: "DC", rating: 86 },
    { name: "Jonathan Tah", pos: "DC", rating: 85 },
    { name: "Josip Stanisic", pos: "DG", rating: 81 },
    { name: "Joshua Kimmich", pos: "MDC", rating: 88 },
    { name: "Aleksandar Pavlovic", pos: "MC", rating: 84 },
    { name: "Jamal Musiala", pos: "MOC", rating: 89 },
    { name: "Luis Diaz", pos: "AG", rating: 86 },
    { name: "Harry Kane", pos: "BU", rating: 91 },
    { name: "Michael Olise", pos: "AD", rating: 89 },
    { name: "Jonas Urbig", pos: "GB", rating: 78 },
    { name: "Min-jae Kim", pos: "DC", rating: 82 },
    { name: "Raphael Guerreiro", pos: "DG", rating: 79 },
    { name: "Leon Goretzka", pos: "MC", rating: 82 },
    { name: "Serge Gnabry", pos: "AD", rating: 82 },
    { name: "Nicolas Jackson", pos: "BU", rating: 81 },
    { name: "Lennart Karl", pos: "MOC", rating: 78 },
  ],
  "Borussia Dortmund": [
    { name: "Gregor Kobel", pos: "GB", rating: 86 },
    { name: "Julian Ryerson", pos: "DD", rating: 80 },
    { name: "Nico Schlotterbeck", pos: "DC", rating: 84 },
    { name: "Waldemar Anton", pos: "DC", rating: 81 },
    { name: "Ramy Bensebaini", pos: "DG", rating: 80 },
    { name: "Pascal Gross", pos: "MDC", rating: 81 },
    { name: "Marcel Sabitzer", pos: "MC", rating: 81 },
    { name: "Julian Brandt", pos: "MOC", rating: 83 },
    { name: "Karim Adeyemi", pos: "AG", rating: 84 },
    { name: "Serhou Guirassy", pos: "BU", rating: 86 },
    { name: "Maximilian Beier", pos: "AD", rating: 81 },
    { name: "Alexander Meyer", pos: "GB", rating: 77 },
    { name: "Niklas Sule", pos: "DC", rating: 80 },
    { name: "Yan Couto", pos: "DD", rating: 79 },
    { name: "Felix Nmecha", pos: "MC", rating: 80 },
    { name: "Carney Chukwuemeka", pos: "MC", rating: 79 },
    { name: "Jobe Bellingham", pos: "MOC", rating: 80 },
    { name: "Fabio Silva", pos: "BU", rating: 80 },
  ],
  "Bayer Leverkusen": [
    { name: "Mark Flekken", pos: "GB", rating: 82 },
    { name: "Nathan Tella", pos: "DD", rating: 80 },
    { name: "Jarell Quansah", pos: "DC", rating: 82 },
    { name: "Loic Bade", pos: "DC", rating: 82 },
    { name: "Alejandro Grimaldo", pos: "DG", rating: 85 },
    { name: "Robert Andrich", pos: "MDC", rating: 81 },
    { name: "Aleix Garcia", pos: "MC", rating: 82 },
    { name: "Malik Tillman", pos: "MOC", rating: 81 },
    { name: "Ernest Poku", pos: "AG", rating: 78 },
    { name: "Patrik Schick", pos: "BU", rating: 84 },
    { name: "Eliesse Ben Seghir", pos: "AD", rating: 82 },
    { name: "Matej Kovar", pos: "GB", rating: 78 },
    { name: "Jeanuel Belocian", pos: "DC", rating: 78 },
    { name: "Edmond Tapsoba", pos: "DC", rating: 83 },
    { name: "Exequiel Palacios", pos: "MC", rating: 81 },
    { name: "Ibrahim Maza", pos: "MOC", rating: 79 },
    { name: "Martin Terrier", pos: "AG", rating: 80 },
    { name: "Christian Kofane", pos: "BU", rating: 77 },
  ],
  "Al-Nassr": [
    { name: "Bento", pos: "GB", rating: 81 },
    { name: "Sultan Al-Ghannam", pos: "DD", rating: 77 },
    { name: "Inigo Martinez", pos: "DC", rating: 83 },
    { name: "Mohamed Simakan", pos: "DC", rating: 81 },
    { name: "Nawaf Boushal", pos: "DG", rating: 75 },
    { name: "Marcelo Brozovic", pos: "MDC", rating: 82 },
    { name: "Angelo Gabriel", pos: "MC", rating: 78 },
    { name: "Joao Felix", pos: "MOC", rating: 83 },
    { name: "Sadio Mane", pos: "AG", rating: 83 },
    { name: "Cristiano Ronaldo", pos: "BU", rating: 88 },
    { name: "Kingsley Coman", pos: "AD", rating: 84 },
    { name: "Raghed Najjar", pos: "GB", rating: 73 },
    { name: "Ali Lajami", pos: "DC", rating: 75 },
    { name: "Abdulelah Al-Amri", pos: "DC", rating: 74 },
    { name: "Abdullah Al-Khaibari", pos: "MC", rating: 75 },
    { name: "Otavio", pos: "MOC", rating: 79 },
    { name: "Wesley", pos: "AD", rating: 77 },
    { name: "Haroune Camara", pos: "BU", rating: 74 },
  ],
  "Inter Miami": [
    { name: "Oscar Ustari", pos: "GB", rating: 76 },
    { name: "Marcelo Weigandt", pos: "DD", rating: 75 },
    { name: "Maximiliano Falcon", pos: "DC", rating: 76 },
    { name: "Noah Allen", pos: "DC", rating: 74 },
    { name: "Jordi Alba", pos: "DG", rating: 79 },
    { name: "Sergio Busquets", pos: "MDC", rating: 80 },
    { name: "Rodrigo De Paul", pos: "MC", rating: 84 },
    { name: "Lionel Messi", pos: "MOC", rating: 90 },
    { name: "Tadeo Allende", pos: "AG", rating: 76 },
    { name: "Luis Suarez", pos: "BU", rating: 78 },
    { name: "Telasco Segovia", pos: "AD", rating: 76 },
    { name: "Rocco Rios Novo", pos: "GB", rating: 72 },
    { name: "Ian Fray", pos: "DD", rating: 73 },
    { name: "Tomas Aviles", pos: "DC", rating: 75 },
    { name: "Yannick Bright", pos: "MC", rating: 74 },
    { name: "Benjamin Cremaschi", pos: "MOC", rating: 76 },
    { name: "Fafa Picault", pos: "AG", rating: 74 },
    { name: "Allen Obando", pos: "BU", rating: 73 },
  ],
  Galatasaray: [
    { name: "Ugurcan Cakir", pos: "GB", rating: 82 },
    { name: "Sallai Roland", pos: "DD", rating: 79 },
    { name: "Davinson Sanchez", pos: "DC", rating: 82 },
    { name: "Abdulkerim Bardakci", pos: "DC", rating: 79 },
    { name: "Ismail Jakobs", pos: "DG", rating: 78 },
    { name: "Lucas Torreira", pos: "MDC", rating: 82 },
    { name: "Gabriel Sara", pos: "MC", rating: 81 },
    { name: "Leroy Sane", pos: "MOC", rating: 84 },
    { name: "Baris Alper Yilmaz", pos: "AG", rating: 80 },
    { name: "Victor Osimhen", pos: "BU", rating: 88 },
    { name: "Yunus Akgun", pos: "AD", rating: 78 },
    { name: "Fernando Muslera", pos: "GB", rating: 77 },
    { name: "Kaan Ayhan", pos: "DC", rating: 76 },
    { name: "Eren Elmali", pos: "DG", rating: 76 },
    { name: "Ilkay Gundogan", pos: "MC", rating: 82 },
    { name: "Mario Lemina", pos: "MDC", rating: 79 },
    { name: "Ahmed Kutucu", pos: "BU", rating: 75 },
    { name: "Mauro Icardi", pos: "BU", rating: 81 },
  ],
  "LOSC Lille": [
    { name: "Berke Ozer", pos: "GB", rating: 80 },
    { name: "Thomas Meunier", pos: "DD", rating: 80 },
    { name: "Aissa Mandi", pos: "DC", rating: 79 },
    { name: "Alexsandro Ribeiro", pos: "DC", rating: 82 },
    { name: "Calvin Verdonk", pos: "DG", rating: 78 },
    { name: "Benjamin Andre", pos: "MDC", rating: 81 },
    { name: "Ayyoub Bouaddi", pos: "MC", rating: 80 },
    { name: "Hakon Haraldsson", pos: "MOC", rating: 80 },
    { name: "Osame Sahraoui", pos: "AG", rating: 80 },
    { name: "Olivier Giroud", pos: "BU", rating: 80 },
    { name: "Matias Fernandez-Pardo", pos: "AD", rating: 78 },
    { name: "Arnaud Bodart", pos: "GB", rating: 76 },
    { name: "Romain Perraud", pos: "DG", rating: 77 },
    { name: "Chancel Mbemba", pos: "DC", rating: 78 },
    { name: "Andre Gomes", pos: "MC", rating: 79 },
    { name: "Nabil Bentaleb", pos: "MC", rating: 78 },
    { name: "Felix Correia", pos: "AG", rating: 77 },
    { name: "Hamza Igamane", pos: "BU", rating: 77 },
  ],
  "OGC Nice": [
    { name: "Yehvann Diouf", pos: "GB", rating: 78 },
    { name: "Jonathan Clauss", pos: "DD", rating: 80 },
    { name: "Moise Bombito", pos: "DC", rating: 78 },
    { name: "Dante", pos: "DC", rating: 78 },
    { name: "Melvin Bard", pos: "DG", rating: 77 },
    { name: "Charles Vanhoutte", pos: "MDC", rating: 76 },
    { name: "Hicham Boudaoui", pos: "MC", rating: 78 },
    { name: "Morgan Sanson", pos: "MOC", rating: 76 },
    { name: "Sofiane Diop", pos: "AG", rating: 78 },
    { name: "Terem Moffi", pos: "BU", rating: 80 },
    { name: "Badredine Bouanani", pos: "AD", rating: 77 },
    { name: "Marcin Bulka", pos: "GB", rating: 78 },
    { name: "Antoine Mendy", pos: "DD", rating: 75 },
    { name: "Ali Abdi", pos: "DG", rating: 76 },
    { name: "Tanguy Ndombele", pos: "MC", rating: 76 },
    { name: "Jeremie Boga", pos: "AG", rating: 78 },
    { name: "Isak Jansson", pos: "AD", rating: 76 },
    { name: "Mohamed-Ali Cho", pos: "BU", rating: 77 },
  ],
  "RC Lens": [
    { name: "Herve Koffi", pos: "GB", rating: 77 },
    { name: "Jonathan Gradit", pos: "DD", rating: 78 },
    { name: "Malang Sarr", pos: "DC", rating: 77 },
    { name: "Jhoanner Chavez", pos: "DC", rating: 76 },
    { name: "Deiver Machado", pos: "DG", rating: 77 },
    { name: "Salis Abdul Samed", pos: "MDC", rating: 77 },
    { name: "Adrien Thomasson", pos: "MC", rating: 78 },
    { name: "Angelo Fulgini", pos: "MOC", rating: 77 },
    { name: "Wesley Said", pos: "AG", rating: 77 },
    { name: "Odsonne Edouard", pos: "BU", rating: 79 },
    { name: "Florian Thauvin", pos: "AD", rating: 81 },
    { name: "Mathew Ryan", pos: "GB", rating: 75 },
    { name: "Ruben Aguilar", pos: "DD", rating: 77 },
    { name: "Matthieu Udol", pos: "DG", rating: 75 },
    { name: "Andy Diouf", pos: "MC", rating: 78 },
    { name: "Mamadou Sangare", pos: "MC", rating: 76 },
    { name: "Rayan Fofana", pos: "BU", rating: 74 },
    { name: "Goduine Koyalipou", pos: "BU", rating: 75 },
  ],
  "Stade Rennais": [
    { name: "Brice Samba", pos: "GB", rating: 81 },
    { name: "Hans Hateboer", pos: "DD", rating: 76 },
    { name: "Anthony Rouault", pos: "DC", rating: 79 },
    { name: "Jeremy Jacquet", pos: "DC", rating: 78 },
    { name: "Quentin Merlin", pos: "DG", rating: 79 },
    { name: "Glen Kamara", pos: "MDC", rating: 78 },
    { name: "Djaoui Cisse", pos: "MC", rating: 77 },
    { name: "Ludovic Blas", pos: "MOC", rating: 79 },
    { name: "Musa Al-Tamari", pos: "AG", rating: 78 },
    { name: "Esteban Lepaul", pos: "BU", rating: 79 },
    { name: "Kader Meite", pos: "AD", rating: 77 },
    { name: "Samba Diouf", pos: "GB", rating: 74 },
    { name: "Lorenz Assignon", pos: "DD", rating: 77 },
    { name: "Christopher Wooh", pos: "DC", rating: 76 },
    { name: "Fabian Rieder", pos: "MOC", rating: 78 },
    { name: "Seko Fofana", pos: "MC", rating: 79 },
    { name: "Breel Embolo", pos: "BU", rating: 79 },
    { name: "Mahdi Camara", pos: "MC", rating: 76 },
  ],
  "RC Strasbourg": [
    { name: "Mike Penders", pos: "GB", rating: 78 },
    { name: "Guela Doue", pos: "DD", rating: 78 },
    { name: "Andrew Omobamidele", pos: "DC", rating: 77 },
    { name: "Lucas Hogsberg", pos: "DC", rating: 77 },
    { name: "Julio Enciso", pos: "MOC", rating: 79 },
    { name: "Valentin Barco", pos: "DG", rating: 79 },
    { name: "Samir El Mourabet", pos: "MDC", rating: 75 },
    { name: "Kendry Paez", pos: "MC", rating: 78 },
    { name: "Sebastian Nanasi", pos: "AG", rating: 79 },
    { name: "Emanuel Emegha", pos: "BU", rating: 81 },
    { name: "Diego Moreira", pos: "AD", rating: 78 },
    { name: "Karl-Johan Johnsson", pos: "GB", rating: 74 },
    { name: "Ismael Doukoure", pos: "DC", rating: 75 },
    { name: "Marvin Senaya", pos: "DD", rating: 74 },
    { name: "Dilane Bakwa", pos: "AD", rating: 79 },
    { name: "Felix Lemarechal", pos: "MC", rating: 76 },
    { name: "Joaquin Panichelli", pos: "BU", rating: 79 },
    { name: "Pape Diong", pos: "MC", rating: 74 },
  ],
  "Toulouse FC": [
    { name: "Guillaume Restes", pos: "GB", rating: 79 },
    { name: "Warren Kamanzi", pos: "DD", rating: 76 },
    { name: "Mark McKenzie", pos: "DC", rating: 78 },
    { name: "Jacob Nicolaisen", pos: "DC", rating: 78 },
    { name: "Charlie Cresswell", pos: "DC", rating: 77 },
    { name: "Cristian Casseres", pos: "MDC", rating: 77 },
    { name: "Vincent Sierro", pos: "MC", rating: 78 },
    { name: "Yann Gboho", pos: "MOC", rating: 78 },
    { name: "Aron Donnum", pos: "AG", rating: 77 },
    { name: "Frank Magri", pos: "BU", rating: 77 },
    { name: "Emersonn", pos: "AD", rating: 76 },
    { name: "Kjetil Haug", pos: "GB", rating: 74 },
    { name: "Anthony Rouault", pos: "DC", rating: 76 },
    { name: "Dayann Methalie", pos: "MC", rating: 73 },
    { name: "Alexis Vossah", pos: "MC", rating: 74 },
    { name: "Shavy Babicka", pos: "AD", rating: 75 },
    { name: "Joshua King", pos: "BU", rating: 75 },
    { name: "Yanis Begraoui", pos: "BU", rating: 73 },
  ],
  "FC Nantes": [
    { name: "Anthony Lopes", pos: "GB", rating: 79 },
    { name: "Kelvin Amian", pos: "DD", rating: 77 },
    { name: "Jean-Charles Castelletto", pos: "DC", rating: 77 },
    { name: "Chidozie Awaziem", pos: "DC", rating: 76 },
    { name: "Nicolas Cozza", pos: "DG", rating: 76 },
    { name: "Pedro Chirivella", pos: "MDC", rating: 77 },
    { name: "Johann Lepenant", pos: "MC", rating: 77 },
    { name: "Louis Leroux", pos: "MOC", rating: 76 },
    { name: "Mostafa Mohamed", pos: "AG", rating: 76 },
    { name: "Matthis Abline", pos: "BU", rating: 79 },
    { name: "Amady Camara", pos: "AD", rating: 73 },
    { name: "Patrik Carlgren", pos: "GB", rating: 73 },
    { name: "Fabien Centonze", pos: "DD", rating: 75 },
    { name: "Nathan Zeze", pos: "DC", rating: 76 },
    { name: "Francis Coquelin", pos: "MC", rating: 76 },
    { name: "Moses Simon", pos: "AG", rating: 78 },
    { name: "Bahereba Guirassy", pos: "BU", rating: 74 },
    { name: "Ignatius Ganago", pos: "BU", rating: 74 },
  ],
  "Stade Brestois": [
    { name: "Radoslaw Majecki", pos: "GB", rating: 78 },
    { name: "Kenny Lala", pos: "DD", rating: 77 },
    { name: "Brendan Chardonnet", pos: "DC", rating: 77 },
    { name: "Soumaila Coulibaly", pos: "DC", rating: 76 },
    { name: "Bradley Locko", pos: "DG", rating: 76 },
    { name: "Hugo Magnetti", pos: "MDC", rating: 77 },
    { name: "Pierre Lees-Melou", pos: "MC", rating: 78 },
    { name: "Romain Del Castillo", pos: "MOC", rating: 78 },
    { name: "Kamory Doumbia", pos: "AG", rating: 77 },
    { name: "Ludovic Ajorque", pos: "BU", rating: 78 },
    { name: "Mama Balde", pos: "AD", rating: 76 },
    { name: "Joris Chotard", pos: "MC", rating: 75 },
    { name: "Massadio Haidara", pos: "DG", rating: 74 },
    { name: "Julien Le Cardinal", pos: "DD", rating: 74 },
    { name: "Rémy Labeau Lascary", pos: "BU", rating: 74 },
    { name: "Pathe Mboup", pos: "AD", rating: 73 },
    { name: "Edimilson Fernandes", pos: "MC", rating: 75 },
    { name: "Jonas Martin", pos: "MC", rating: 73 },
  ],
};
